#!/usr/bin/env sh
repo_root="$(git rev-parse --show-toplevel)"
tool_root="$repo_root/RadMapping+"
export PATH="$tool_root/node_modules/.bin:$PATH"
"$tool_root/node_modules/.bin/lint-staged" --cwd "$repo_root"
